version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: true
  - source: /application.zip
    destination: /home/ec2-user/app
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
