version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ec2-user/app
  - source: /scripts
    destination: /home/ec2-user/app/scripts
hooks:
  ApplicationStop:
    - location: /home/ec2-user/app/scripts/stop_application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ec2-user/app/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/app/scripts/start_application.sh
      timeout: 300
      runas: root