version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python -m pip install --upgrade pip
      - pip install -r app/requirements.txt

  pre_build:
    commands:
      - echo "Running tests..."
      - cd app && python -m pytest && cd ..

  build:
    commands:
      - echo "Building application..."

artifacts:
  name: BuildArtifact.zip
  files:
    - appspec.yml
    - scripts/**
    - app/**
  discard-paths: no
